### ISSUE TITLE
rebase over 4.x

### ISSUE THREAD

**Issue by floion** [fedux/linux#1]
Hi,
I see here https://archlinuxarm.org/forum/viewtopic.php?f=63&t=9105 that you were working on rebasing the Odroid C1 kernel on 4.x
Did you make any headwinds with that?
Thanks

**Comment by fedux** [comment]
Hi! I switched my efforts to the mainline version from http://linux-meson.com/ 

My odroid-c1 is currently running:
 ```
$ uname -a
Linux kaoz-ber 4.16.2-1-ARCH #2 SMP Sun Apr 15 20:57:57 CEST 2018 armv7l GNU/Linux
```
I have a custom PKGBUILD for it that I can share with you if you're interested.

**Comment by floion** [comment]
So it's just the mainline kernel that you use from kernel.org?

**Comment by fedux** [comment]
Yes, 4.16 plus:
```
  -> Found 1001-RFC-ARM-dts-meson8b-odroidc1-add-microSD-support.patch
  -> Found 1002-RFC-v1-pinctrl-meson-meson8b-fix-requesting-GPIOs-greater-than-GPIOZ_3.patch
  -> Found 1003-v2-2-2-ARM-dts-meson8b-the-CBUS-GPIO-controller-only-has-83-GPIOs.patch
  -> Found 1004-v2-1-2-ARM-dts-meson8b-extend-ethernet-controller-description.patch
  -> Found 1005-v2-2-2-ARM-dts-meson8b-odroidc1-ethernet-support.patch
```
, and customized boot.ini:
```
$ cat /boot/boot.ini 
ODROIDC-UBOOT-CONFIG

ext4load mmc 0:1 0x21000000 boot/uImage
ext4load mmc 0:1 0x22000000 boot/uInitramfs-linux.img
ext4load mmc 0:1 0x21800000 boot/dtbs/meson8b-odroidc1.dtb

setenv bootargs "root=/dev/mmcblk0p1 rootwait rw console=ttyAML0,115200"

bootm 0x21000000 0x22000000 0x21800000
```

**Comment by floion** [comment]
Thanks. I am using 4.16.2 also, but have some SD issues after a while (a few hours, with the rootfs loaded from SD card):

[ 6797.573162] print_req_error: I/O error, dev mmcblk0, sector 2497560
[ 6797.573203] mmc0: card aaaa removed

after this it's unusable.

I am also running a kernel with https://patchwork.kernel.org/patch/10181185/ and https://patchwork.kernel.org/patch/10183619/ but not sure if they are the latest versions. Can you share the patches you listed above? I could maybe check if they contain the same changes with the ones I linked

Thanks

**Comment by fedux** [comment]
First two are the same. Full patch-set: https://gist.github.com/fedux/73cd59e619d37f2bfe1d19106e515122

I've been running these kernels with no problems for more than a month already (since 4.16-rcX).

**Comment by floion** [comment]
Thanks for the patches.
Are you running from SD card or from eMMC? What is the filesystem you are using?

**Comment by fedux** [comment]
```
[    0.000000] Kernel command line: root=/dev/mmcblk0p1 rootwait rw console=ttyAML0,115200
[    1.673606] platform c1108c20.mmc:slot@1: Got CD GPIO
[    1.806728] mmc0: new high speed SDHC card at address aaaa
[    1.812730] mmcblk0: mmc0:aaaa SC16G 14.8 GiB 
[    1.822478]  mmcblk0: p1
[    3.179777] EXT4-fs (mmcblk0p1): mounting ext3 file system using the ext4 subsystem
[    3.208999] EXT4-fs (mmcblk0p1): mounted filesystem with ordered data mode. Opts: (null)
```

IIRC these one: https://www.amazon.de/SanDisk-Ultra-microSDHC-Speicherkarte-Adapter/dp/B073S9SFK2/ref=pd_lpo_vtph_147_tr_img_2?_encoding=UTF8&psc=1&refRID=BBW6FEW5ZBB9HH4PG68F

**Comment by floion** [comment]
Thanks for all the info
